# Generated by Django 5.1.4 on 2025-01-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileInfo', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('share_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='分享id')),
                ('valid_type', models.IntegerField(verbose_name='有效期类型')),
                ('expire_time', models.DateTimeField(verbose_name='失效时间')),
                ('share_time', models.DateTimeField(auto_now_add=True, verbose_name='分享时间')),
                ('show_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('code', models.CharField(max_length=5, verbose_name='分享的提取码:')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FileInfo.fileinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'file_share',
            },
        ),
    ]
