# Generated by Django 5.1.6 on 2025-02-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FileInfo', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConverSations',
            fields=[
                ('conversation_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='会话id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建会话时间')),
                ('user1_delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除记录的时间')),
                ('user2_delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除记录的时间')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_conversations', to='User.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_conversations', to='User.user')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConverSationsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True, verbose_name='加入会话时间')),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.conversations')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'conversations_user',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='消息id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建消息时间')),
                ('content', models.CharField(max_length=200, null=True, verbose_name='消息内容')),
                ('status', models.IntegerField(default=0, verbose_name='消息已读状态')),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.conversations')),
                ('file_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FileInfo.fileinfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
