# Generated by Django 5.1.4 on 2025-01-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversations',
            name='user1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user1_conversations', to='User.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversations',
            name='user1_delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除记录的时间'),
        ),
        migrations.AddField(
            model_name='conversations',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2_conversations', to='User.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversations',
            name='user2_delete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除记录的时间'),
        ),
    ]
