# Generated by Django 5.1.4 on 2025-01-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_conversations_user1_conversations_user1_delete_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(default=0, verbose_name='消息已读状态'),
        ),
    ]
