# Generated by Django 5.1.4 on 2025-01-18 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('config_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='设置的id')),
                ('user_space', models.BigIntegerField(verbose_name='用户的默认空间大小')),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='用户id')),
                ('nick_name', models.CharField(max_length=15, unique=True, verbose_name='用户昵称')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('avatar', models.FileField(default='avatar/default.png', upload_to='avatar', verbose_name='用户头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login_time', models.DateTimeField(null=True, verbose_name='最后登陆时间')),
                ('status', models.BooleanField(default=True, verbose_name='用户状态')),
                ('use_space', models.BigIntegerField(default=0, verbose_name='已使用空间')),
                ('total_space', models.BigIntegerField(default=0, verbose_name='总空间')),
                ('identity', models.BooleanField(default=False, verbose_name='身份')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friend_id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='好友状态id')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1_friend', to='User.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2_friend', to='User.user')),
            ],
            options={
                'db_table': 'friend',
            },
        ),
    ]
