# Generated by Django 5.1.1 on 2024-10-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='文件id')),
                ('file_md5', models.CharField(default='', max_length=32, verbose_name='文件md5值')),
                ('file_pid', models.CharField(default='0', max_length=40, verbose_name='父级id')),
                ('file_size', models.IntegerField(null=True, verbose_name='文件大小')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file_cover', models.ImageField(default='', upload_to='cover', verbose_name='文件封面')),
                ('file_path', models.FileField(default='', upload_to='file', verbose_name='文件位置')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('folder_type', models.IntegerField(verbose_name='文件类型')),
                ('file_category', models.IntegerField(null=True, verbose_name='文件分类')),
                ('file_type', models.IntegerField(null=True, verbose_name='文件具体分类')),
                ('status', models.IntegerField(default=2, verbose_name='文件状态')),
                ('recovery_time', models.DateTimeField(null=True, verbose_name='进入回收站时间')),
                ('del_flag', models.IntegerField(default=2, verbose_name='文件是否删除')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'db_table': 'file_info',
            },
        ),
    ]
